jobs:
  include:
    - stage: build phase 1
      script:
      - echo ${TRAVIS_BRANCH}
      - echo ${TRAVIS_BRANCH//\//--}
      - echo ${TRAVIS_PULL_REQUEST}
      - echo ${TRAVIS_PULL_REQUEST_BRANCH}
      - echo ${PWD}
      - echo `./Docker/get_tpls_version.sh --amanzi_source_dir=${PWD}`
      - cd Docker
      - export AMANZI_TPLS_VER=`./get_tpls_version.sh`
    - stage: build phase 2
      script:
      - cd Docker
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - stage: test
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker run --rm $DOCKER_USERNAME/amanzi:${TRAVIS_BRANCH//\//--}-temp-build-stage-2 /bin/bash -c "cd ~/amanzi_builddir/amanzi; ctest -R marshak -V"
